server:
  port: 1001
spring:
  application:
    name: geteway
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos地址
    gateway:
      routes:
        - id: goods-service #路由标识 必须唯一
          uri: lb://goodsservice #路由的目标地址
          predicates: #路由断言  判断请求是否符合规则
            - Path=/goods/** #路径断言：判断路径是否是以/user开头如果是则符合
#          filters:  #路由过滤器
#            - AddRequestHeader=Truth,Itcast is freaking aowsome!  #添加请求头
        - id: goodsorder-service
          uri: lb://goodsorderservice
          predicates:
            - Path=/goods/**
            - Path=/goodscategory/**
            #在设置时间之前使用 之后报错
            - Before=2031-02-12T15:14:31.433+08:00[Asia/Shanghai]
      #定义所有路由默认开启请求头
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking aowsome!  #添加请求头
        - AddRequestHeader=origin,gateway
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期