server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: goodsorderservice
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos服务地址
    sentinel:
      transport:
        dashboard: localhost:8080  #sentinel控制台地址
      web-context-unify: false  #关闭context整合
mybatis:
  type-aliases-package: cn.itcast.goods.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
goodsservice:  #要做配置的服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
ribbon:
  eager-load:
    enabled: true
    clients:
      - goodsservice

#feign优化
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  sentinel:
    enabled: true

#定义日志级别
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FUL