server:
  port: 1001
spring:
  application:
    name: geteway
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos地址
    gateway:
      routes:
        - id: goods-service #路由标识 必须唯一
          uri: lb://goodsservice #路由的目标地址
          predicates: #路由断言  判断请求是否符合规则
            - Path=/goods/**
        - id: goodsorder-service
          uri: lb://goodsorderservice
          predicates:
            - Path=/goods/**
            - Path=/goodscategory/**
            - Before=2031-02-12T15:14:31.433+08:00[Asia/Shanghai]
      #定义所有路由默认开启请求头
      default-filters:
        - AddRequestHeader=Truth,Itcast is freaking aowsome!
        - AddRequestHeader=origin,gateway
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000